version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: authenticator
      POSTGRES_PASSWORD: authenticator
      POSTGRES_DB: authenticator
    networks:
      authenticator:
        ipv4_address: 172.0.0.10
    volumes:
      - ./data/db:/var/lib/postgres

networks:
  authenticator:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24